In [8]:
import numpy as np 
import pandas as pd
a= np.matrix([[1,2,3,4,],
             [5,5,6,7],
             [1,4,2,3],
             [5,3,2,1],
             [8,1,2,2]])
df=pd.DataFrame(a,columns=['n1','n2','n3','n4'])
df


n1  n2  n3  n4
0   1   2   3   4
1   5   5   6   7
2   1   4   2   3
3   5   3   2   1
4   8   1   2   2

In [3]:
z =(df-df.mean())/df.std() #standardize the dataset
z

n1        n2        n3        n4
0 -1.000000 -0.632456  0.000000  0.260623
1  0.333333  1.264911  1.732051  1.563740
2 -1.000000  0.632456 -0.577350 -0.173749
3  0.333333  0.000000 -0.577350 -1.042493
4  1.333333 -1.264911 -0.577350 -0.608121

In [11]:
#find eigen value and vector 
x=np.matrix(z)
c=(x-x.mean()).T*(x-x.mean())/(len(x)) # covactor
print (c)
eig=np.linalg.eig(c)
eig


[[ 0.8        -0.25298221  0.03849002 -0.14479075]
 [-0.25298221  0.8         0.51120772  0.49449803]
 [ 0.03849002  0.51120772  0.8         0.75235479]
 [-0.14479075  0.49449803  0.75235479  0.8       ]]


(array([2.01263459, 0.8522308 , 0.31510964, 0.02002497]),
 matrix([[ 0.16195986, -0.91705888, -0.30707099,  0.19616173],
         [-0.52404813,  0.20692161, -0.81731886,  0.12061043],
         [-0.58589647, -0.3205394 ,  0.1882497 , -0.72009851],
         [-0.59654663, -0.11593512,  0.44973251,  0.65454704]]))

In [9]:
# pick k eigenvalues and from a matrix of eigen vectors
e_vector =eig[1][:,:2]
e_value =eig[0][:2]
print (e_value)
print (e_vector)

[2.01263459 0.8522308 ]
[[ 0.16195986 -0.91705888]
 [-0.52404813  0.20692161]
 [-0.58589647 -0.3205394 ]
 [-0.59654663 -0.11593512]]


In [6]:
pca=x*e_vector
pd.DataFrame(pca,columns =['fn1','fn2'])

fn1       fn2
0  0.014003  0.755975
1 -2.556534 -0.780432
2 -0.051480  1.253135
3  1.014150  0.000239
4  1.579861 -1.228917